#!/bin/zsh

#############   Montiors   ###############

bspc monitor -d 1 2 3 4 5 6 7 8 9

#############   Variables   ###############

# apps
export WM_DEFAULT_TERMINAL=alacritty
export WM_DEFAULT_BROWSER=firefox
export WM_NETWORK_GUI=iwgtk

function capitalize {
    echo $1 | sed -e "s/\b\(.\)/\u\1/g"
}

# floating apps
WM_FLOATING_APPS="feh mpv Iwgtk flameshot PCSX2 *:SPLASH"

#############   Configuration   ###############
bspc config window_gap                    8
bspc config top_padding                   26
bspc config top_monocle_padding           0
bspc config border_width                  0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config paddingless_monocle           true
bspc config focus_follows_pointer         true
bspc config ignore_ewmh_focus             true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_follows_monitor       true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# theme
bspc config active_border_color "#767c82"
bspc config focused_border_color "#767c82"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

# default desktop for apps
bspc rule -a $(capitalize $WM_DEFAULT_BROWSER) -o desktop=3
bspc rule -a "Telegram" -o desktop=8

# floating apps
for app in $WM_FLOATING_APPS; do
    bspc rule -a "$app" state='floating'
done

# default desktop
bspc desktop -f 1

# AUTOSTART
~/.config/bspwm/autostart &
